# Generated by Django 5.2.2 on 2025-06-27 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='交易對符號')),
                ('interval', models.CharField(default='1m', max_length=10, verbose_name='K線週期')),
                ('precision', models.IntegerField(default=0, verbose_name='數量精度')),
                ('average_atr', models.FloatField(blank=True, null=True, verbose_name='歷史平均ATR')),
                ('consecutive_stop_loss', models.IntegerField(default=0, verbose_name='連續止損次數')),
                ('last_trade_time', models.DateTimeField(blank=True, null=True, verbose_name='上次交易時間')),
            ],
            options={
                'verbose_name': '交易對',
                'verbose_name_plural': '交易對',
            },
        ),
        migrations.CreateModel(
            name='StrategyCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='策略組合名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='策略條件')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否啟用')),
                ('combo_mode', models.CharField(choices=[('aggressive', '激進 (Aggressive)'), ('balanced', '平衡 (Balanced)'), ('conservative', '保守 (Conservative)'), ('auto', '自動判斷 (Auto-detect)'), ('custom', '自定義 (Custom)')], default='balanced', max_length=20, verbose_name='啟用組合包模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '策略組合',
                'verbose_name_plural': '策略組合',
            },
        ),
        migrations.CreateModel(
            name='TraderConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='配置鍵')),
                ('value', models.TextField(verbose_name='配置值')),
                ('value_type', models.CharField(default='str', help_text='例如: str, int, float, bool, list, dict', max_length=20, verbose_name='值類型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '交易配置',
                'verbose_name_plural': '交易配置',
            },
        ),
        migrations.CreateModel(
            name='TraderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trading_enabled', models.BooleanField(default=True, verbose_name='交易是否啟用')),
                ('stop_signal_received', models.BooleanField(default=False, verbose_name='是否收到停止信號')),
                ('last_daily_reset_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='上次每日重置日期')),
            ],
            options={
                'verbose_name': '交易員狀態',
                'verbose_name_plural': '交易員狀態',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('trading_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trading_api.tradingpair', verbose_name='交易對')),
                ('active', models.BooleanField(default=False, verbose_name='是否活躍')),
                ('side', models.CharField(max_length=4, verbose_name='持倉方向')),
                ('entry_price', models.FloatField(verbose_name='開倉價格')),
                ('quantity', models.FloatField(verbose_name='持倉數量')),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開倉時間')),
            ],
            options={
                'verbose_name': '持倉',
                'verbose_name_plural': '持倉',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易時間')),
                ('side', models.CharField(max_length=4, verbose_name='交易方向')),
                ('entry_price', models.FloatField(verbose_name='開倉價格')),
                ('exit_price', models.FloatField(verbose_name='平倉價格')),
                ('quantity', models.FloatField(verbose_name='交易數量')),
                ('pnl', models.FloatField(verbose_name='損益')),
                ('reason', models.CharField(max_length=100, verbose_name='平倉原因')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_api.tradingpair', verbose_name='交易對')),
            ],
            options={
                'verbose_name': '交易記錄',
                'verbose_name_plural': '交易記錄',
                'ordering': ['-trade_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('pnl', models.FloatField(default=0.0, verbose_name='當日累積損益')),
                ('start_balance', models.FloatField(default=0.0, verbose_name='當日起始資金')),
                ('max_daily_loss_pct', models.FloatField(default=0.25, verbose_name='最大當日虧損百分比')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_api.tradingpair', verbose_name='交易對')),
            ],
            options={
                'verbose_name': '每日統計',
                'verbose_name_plural': '每日統計',
                'unique_together': {('trading_pair', 'date')},
            },
        ),
    ]
