# Generated by Django 5.2.2 on 2025-08-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0002_traderstatus_trade_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityPauseStatus',
            fields=[
                ('trading_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trading_api.tradingpair', verbose_name='交易對')),
                ('is_paused', models.BooleanField(default=False, verbose_name='是否因波動率暫停')),
                ('pause_start_time', models.DateTimeField(blank=True, null=True, verbose_name='暫停開始時間')),
                ('pause_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='暫停原因')),
                ('current_atr_ratio', models.FloatField(default=1.0, verbose_name='當前ATR比率')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '波動率暫停狀態',
                'verbose_name_plural': '波動率暫停狀態',
            },
        ),
    ]
