# Generated by Django 5.2.2 on 2025-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='策略組合名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='策略條件')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否啟用')),
                ('combo_mode', models.CharField(max_length=20, verbose_name='組合模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
    ]
